INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (1, '1081 - Manufacture of sugar', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (2, 'Total UK manufacturer sales of products in this product group', null, 'Prodcom Elements');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (3, '1051 - Operation of dairies & cheesemaking', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (4, 'Non production income', null, 'Prodcom Elements');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (5, '1041 - Manufacture of oils and fats', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (6, 'Work done', null, 'Prodcom Elements');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (7, '1083 - Processing of tea & coffee', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (8, 'Net carry in/carry out', null, 'Prodcom Elements');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (9, '1089 - Manufacture of other food products n.e.c.', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (10, '10 - Manufacture of food products', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (11, 'Waste Products', null, 'Prodcom Elements');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (12, '1073 - Manufacture of macaroni, noodles, couscous and similar farinaceous products', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (13, '1039 - Other processing and preserving of fruit and vegetables', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (14, 'Merchanted goods', null, 'Prodcom Elements');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (15, '1071 - Manufacture of bread; manufacture of fresh pastry goods and cakes', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (16, '1020 - Processing and preserving of fish, crustaceans and molluscs', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (17, 'Total turnover of businesses classified to this industry', null, 'Prodcom Elements');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (18, '1106 - Manufacture of malt', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (19, 'UK manufacturer sales of individual products listed in this product group', null, 'Prodcom Elements');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (20, '1101 - Distilling, rectifying and blending of spirits', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (21, '1072 - Manufacture of rusks and biscuits; manufacture of preserved pastry goods and cakes', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (22, '1011 - Processing and preserving of meat', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (23, 'All other income', null, 'Prodcom Elements');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (24, '1092 - Manufacture of prepared pet foods', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (25, '0891 - Mining of chemical and fertiliser minerals', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (26, '1084 - Manufacture of condiments and seasonings', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (27, '12 - Manufacture of tobacco products', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (28, '1091 - Manufacture of prepared feeds for farm animals', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (29, '1031 - Processing and preserving of potatoes', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (30, '1061 - Manufacture of grain mill products', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (31, '08 - Other mining and quarrying', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (32, 'UK manufacturer sales LABEL', null, 'Prodcom Elements');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (33, '1032 - Manufacture of fruit and vegetable juice', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (34, '1013 - Production of meat and poultry meat products', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (35, '1105 - Manufacture of beer', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (36, '1200 - Manufacture of tobacco products', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (37, '1102 - Manufacture of wine from grapes', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (38, '0899 - Other mining and quarrying n.e.c', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (39, '1085 - Manufacture of prepared meals and dishes', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (40, '11 - Manufacture of beverages', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (41, '1104 - Manufacture of other non-distilled fermented beverages', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (42, '1086 - Manufacture of homogenised food preparations and dietetic food', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (43, '13 - Manufacture of textiles', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (44, '1012 - Processing and preserving of poultry meat', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (45, '1082 - Manufacture of cocoa, chocolate & sugar confectionery', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (46, '1103 - Manufacture of cider and other fruit wines', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (47, '1107 - Manufacture of soft drinks; production of mineral waters and other bottled waters', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (48, '1052 - Manufacture of ice cream', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (49, '1062 - Manufacture of starches and starch products', null, 'NACE');
INSERT INTO public.category (category_id, name, fk_category_id, concept_system) VALUES (50, '1042 - Manufacture of margarine and similar edible fats', null, 'NACE');