INSERT INTO public.geographic_area_type (geographic_area_type) VALUES ('UK');
INSERT INTO public.geographic_area_type (geographic_area_type) VALUES ('GB');
INSERT INTO public.geographic_area_type (geographic_area_type) VALUES ('EW');
INSERT INTO public.geographic_area_type (geographic_area_type) VALUES ('COUNTRY');
INSERT INTO public.geographic_area_type (geographic_area_type) VALUES ('REGION');
INSERT INTO public.geographic_area_type (geographic_area_type) VALUES ('COUNTY');
INSERT INTO public.geographic_area_type (geographic_area_type) VALUES ('METROPOLITAN COUNTY');
INSERT INTO public.geographic_area_type (geographic_area_type) VALUES ('UNITARY AUTHORITY');
INSERT INTO public.geographic_area_type (geographic_area_type) VALUES ('LONDON BOROUGH');
INSERT INTO public.geographic_area_type (geographic_area_type) VALUES ('INNER AND OUTER LONDON');
INSERT INTO public.geographic_area_type (geographic_area_type) VALUES ('NON-METROPOLITAN DISTRICT');
INSERT INTO public.geographic_area_type (geographic_area_type) VALUES ('METROPOLITAN DISTRICT');
INSERT INTO public.geographic_area_type (geographic_area_type) VALUES ('METROPOLITAN BOROUGH');
INSERT INTO public.geographic_area_type (geographic_area_type) VALUES ('COUNCIL AREA');
INSERT INTO public.geographic_area_type (geographic_area_type) VALUES ('MSOA');
INSERT INTO public.geographic_area_type (geographic_area_type) VALUES ('WPC');
INSERT INTO public.geographic_area_type (geographic_area_type) VALUES ('NUTS0');
INSERT INTO public.geographic_area_type (geographic_area_type) VALUES ('NUTS1');
INSERT INTO public.geographic_area_type (geographic_area_type) VALUES ('NUTS2');
INSERT INTO public.geographic_area_type (geographic_area_type) VALUES ('NUTS3');